server:
  port: 80
  context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://176.20.14.219:3306/logistic
    username: root
    password: root
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  mail:  
    host: smtp.163.com
    username: tongtianlogistics@163.com
    password: tongtian123
    properties:  
      mail:  
        smtp: 
          auth: true  
          starttls:  
            enable: true  
            required: true 
             
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mappers/*.xml
  
  
